### ISSUE TITLE
As an experienced user, I can create custom aliases to commands

### ISSUE THREAD

**Issue by SakuraBlossom** [AY1920S1-CS2103T-T09-3/main#15]

**Comment by SakuraBlossom** [comment]
With the use of autocomplete. The alias command does not seem to be neccessary.

**Comment by CarbonGrid** [comment]
I think we can invalidate this because probably only Linux power users would prefer such flexibility. Implementing it is a rather minor improvement and would be rather hacky if we are not reworking the parser as current algorithm is not dynamic enough to insert new command keywords. This means we would be substituting any keyword that is an alias to its equivalence before executed by logic.
